### ISSUE TITLE
Unrecognized .pp files

### ISSUE THREAD

**Issue by tiagopsilva** [alefragnani/language-pascal#12]
Hi

The package don't apply syntax highlight in .pp files on my Atom.

.pp file without syntax highlight

![without syntax highlight](https://cloud.githubusercontent.com/assets/14366064/10532213/ec129444-7391-11e5-8391-54430fcb8b31.png)

.pas with sintax highlight

![with syntax highlight](https://cloud.githubusercontent.com/assets/14366064/10532254/807c04da-7392-11e5-80d6-70361af0939d.png)

Thanks for package

**Comment by alefragnani** [comment]
You are right. `.pp` files aren't supported :-(. Unfortunately I'm don't use FreePascal/Lazarus that much, so there are some missing pieces yet. If you see any other problem, feel free add new issues.

I will add `.pp` extension tomorrow and publish a new version.

**Comment by trx222** [comment]
Better would be if one can add file extensions by config because I am using .inc also as pascal files ... is it possible to add this?

**Comment by alefragnani** [comment]
Hi @trx222 ,

I don't remember seeing such feature on Atom, neither via another package. So, to recognize `.inc` files, the Pascal package should be updated, just like it was to recognize `.pp` files.

Feel free to open a new PR, and follow the idea of [this commit](https://github.com/alefragnani/atom-language-pascal/commit/fd8ac8936bb0dd49633d8c77370c4c852b3d5f72). It should be fairly easy.

Hope this helps

**Comment by trx222** [comment]
Hi  alefragnani, thanks for your reply. I just know the possibility to config syntax-highlighter from eclipse or other texteditors that I've used before.  I will see if I can add the extension like you wrote - maybe I also find time to check a config possibility. Thanks again and best regards.
