### ISSUE TITLE
don't let strings go over end-of-line

### ISSUE THREAD

**Issue by stijnsanders** [alefragnani/language-pascal#2]
If you have only one `'` on a line, the grammar detects a string is started, that is correct.

But since the closing `'` is missing, syntax highlighting shows all the following lines as a string as well. Most Pascal compilers will throw an error about the unclosed string, so is there a way to change the grammar to show a string from a `'` to the next `'` *or* the first end-of-line?

**Comment by alefragnani** [comment]
Right, I could reproduce the problem. Strangely the same problem occurs with a lot of languages. Probably because a lot of them has also been converted from TextMate/Sublime, like this one.

I'm not a grammar specialist but I will try to fix it :smile:

Thanks for the report.

**Comment by stijnsanders** [comment]
Thank you!
