### ISSUE TITLE
Lazarus file extensions?

### ISSUE THREAD

**Issue by rugk** [alefragnani/language-pascal#8]
What about adding the Lazarus file extensions like `.lpr` and `.lmf` (form)?

**Comment by alefragnani** [comment]
No problem, if they work with the actual grammar. Could you please confirm? Also,  isn't `.lfm` instead?

**Comment by rugk** [comment]
You're right `.lfm`instead of `.lmf` (this was a typo).
And AFAIK they use the usual Pascal grammar.

But instead of relying on my assumptions (which are only based on a quick look over the files) I would rather have a look at this here: http://wiki.freepascal.org/File_extensions
