### ISSUE TITLE
Default tab length: 2 spaces

### ISSUE THREAD

**Issue by rugk** [alefragnani/language-pascal#9]
[According to the FreePascal wiki](http://wiki.freepascal.org/Coding_style) the tab length to use should be 2.
Can you change this setting?

Or are there other doc's which recommend another value?

**Comment by alefragnani** [comment]
I have no problem with it :+1:. The [Object Pascal Style Guide](http://edn.embarcadero.com/article/10280) also defines 2 as tab length. 

I never worried about it because I use Atom with tab length defined as 2 for all languages.

Will be updated on the next release.
